# site settings
title: Great New Site
author: 0xdecaf2bad
name: 0xdecaf2bad
email: me@here.com
description: "Great site about stuff"

#Build settings
remote_theme: jekyll/minima

minima:
  skin: dark
  
